In [1]:
import pandas as pd

In [5]:
train = pd.read_csv("train_5000.tsv" , delimiter='\t')
test = pd.read_csv("test_5000.tsv" , delimiter='\t')

In [6]:
train

,Unnamed: 0,drugName,condition,review,rating,date,usefulCount
0,127888,Phentermine,Weight Loss,"""I started taking Phentermine just a little ov...",10.0,"November 26, 2016",24
1,197702,Desvenlafaxine,Depression,"""I have had depression for years due to situat...",10.0,"July 25, 2009",31
2,40759,Leuprolide,Endometriosis,"""I was actually surprised to learn I had stage...",8.0,"December 21, 2011",31
3,208098,Zyclara,Keratosis,"""Have used this for one week but began to have...",7.0,"January 20, 2013",17
4,161657,Diphenhydramine,Allergic Reactions,"""Experienced an allergic reaction during dinne...",10.0,"April 11, 2015",20
...,...,...,...,...,...,...,...
4995,172298,Clonazepam,Panic Disorde,"""Although this drug can help with panic attack...",1.0,"August 23, 2017",28
4996,228393,Butrans,Chronic Pain,"""Chronic back pain after a motor cycle acciden...",2.0,"August 21, 2013",44
4997,115267,Diazepam,NaN,"""I have found this drug also acts as a muscle ...",9.0,"March 16, 2008",43
4998,5427,Penciclovir,Cold Sores,"""I&#039;ve had cold sores for as long as I can...",10.0,"May 29, 2017",0
4999,111342,Ledipasvir / sofosbuvir,Hepatitis C,"""I waited for 14 months after a positive HCV 1...",10.0,"April 27, 2016",18

In [7]:
test

,Unnamed: 0,drugName,condition,review,rating,date,usefulCount
0,192361,Drospirenone / ethinyl estradiol,Birth Control,"""No side effects(nausea, headaches,etc) \r\r\n...",9.0,"May 5, 2015",3
1,202481,Lithium,Bipolar Disorde,"""When I originally got sick with insomnia and ...",8.0,"July 7, 2014",33
2,42681,Concerta,ADHD,"""As an adult with ADHD Concerta is the way to ...",8.0,"August 9, 2009",40
3,138297,Orthovisc,Osteoarthritis,"""What a waste of money I paid a copay of $400 ...",1.0,"June 20, 2015",21
4,76754,Lorcaserin,Weight Loss,"""Took first pill yesterday. Noticed almost imm...",1.0,"June 22, 2016",19
...,...,...,...,...,...,...,...
4995,127049,Metoclopramide,Gastroparesis,"""Side effects far outweigh any benefit from th...",1.0,"June 1, 2010",34
4996,18564,Zolpidem,Insomnia,"""My insomnia comes from anxiety issues when I ...",10.0,"February 26, 2008",217
4997,217482,Clarithromycin,Bronchitis,"""I didn&#039;t experience or notice any of the...",8.0,"March 26, 2015",18
4998,47576,Tapentadol,Pain,"""I could not deal with the side effects of Oxy...",8.0,"October 10, 2014",68
4999,215115,Fexofenadine,Urticaria,"""It&#039;s the best medicine for hives. I took...",10.0,"February 26, 2011",49

Whenever you’re dealing with customer reviews, a good practice is to check the number of words in each review. A review might be just a single word like “Great!” or a full-blown essay with thousands of words, and depending on the use case you’ll need to handle these extremes differently. To compute the number of words in each review, we’ll use a rough heuristic based on splitting each text by whitespace.

Let’s define a simple function that counts the number of words in each review:

In [11]:
def compute_rev_len(example):
    return len(example.split())

train["review_len"] = train["review"].apply(compute_rev_len)

In [12]:
train["review"][0]

'"I started taking Phentermine just a little over a month ago weighing in at 307. My doctor started me out with half a 37.5 mg pill 2x a day. I immediately felt the medicine start working, the jittery jumping out of your skin feeling and I had a lot of energy the first few days. I sweated profusely and had to have water by my side at all times.  I felt the meds even out and by the 5th day I was asking my doctor to let me take a whole pill once a day. I make sure I take my dose early when I first wake up. So in about 5 weeks I have dropped down to 293. This drug is life changing for me. I should be on disability and I&#039;m in chronic pain but this medicine has seemed to help me beyond the appetite suppressant. I&#039;m a 40 year old female with hope!"'

Let’s use the train[train["review_len"] > 30]  to remove reviews that contain fewer than 30 words. Similarly to what we did with the condition column, we can filter out the very short reviews by requiring that the reviews have a length above this threshold:

In [16]:
train = train[train["review_len"] > 30]

The last thing we need to deal with is the presence of HTML character codes in our reviews. We can use Python’s html module to unescape these characters, like so:

In [19]:
import html

text = "I&#039;m a transformer called BERT"
html.unescape(text)

"I'm a transformer called BERT"

In [ ]:
def remove_html(example):
    return html.unescape(example)

train = remove_html(train["review"])